version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email)
      - docker pull ${REPOSITORY_URI}:latest || true
  build:
    commands:
      - docker build -t sample --cache-from ${REPOSITORY_URI}:latest .
      - docker tag sample:latest ${REPOSITORY_URI}:latest
  post_build:
    commands:
      - docker push ${REPOSITORY_URI}:latest
